// Generated by CoffeeScript 1.10.0

/*
paras: what to log, if an object then it will be deeply inspected
 */

(function() {
  var debug,
    slice = [].slice;

  if (typeof process === 'undefined') {
    debug = false;
  } else {
    debug = process.env['NODE_DEBUG'] ? true : false;
  }

  module.exports = function() {
    var e, file, inspect, locLine, m, msg, offsets, para, paras, ref, ts;
    paras = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    ts = (function() {
      var dateTs, i, j, pad, ref, sms, sts;
      dateTs = new Date();
      sts = dateTs + "";
      sms = '' + dateTs.getMilliseconds();
      pad = 3 - sms.length;
      for (i = j = 0, ref = pad; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        sms = '0' + sms;
      }
      return sts.slice(4, 24) + "." + sms + sts.slice(24, 33);
    })();
    inspect = function(obj, opt) {
      var util;
      if (typeof window === 'undefined') {
        util = require('util');
        return util.inspect(obj, opt);
      } else if (module.exports.inspect) {
        return module.exports.inspect(obj, opt);
      } else {
        return JSON.stringify(obj);
      }
    };
    msg = ((function() {
      var j, len, results;
      results = [];
      for (j = 0, len = paras.length; j < len; j++) {
        para = paras[j];
        results.push(typeof para === "object" ? inspect(para, {
          depth: 10
        }) : "" + para);
      }
      return results;
    })()).join('');
    if (debug) {
      e = new Error("");
      locLine = e.stack.split("\n")[2];
      m = /\((.*?):(\d+:\d+)\)/.exec(locLine);
      if (!m) {
        m = /at (.*?):(\d+:\d+)/.exec(locLine);
      }
      if (m) {
        ref = [m[1], m[2]], file = ref[0], offsets = ref[1];
        return console.log("[" + ts + "](" + file + ":" + offsets + ") " + msg + " ");
      } else {
        return console.log("[" + ts + "](" + e.stack + ") " + msg + " ");
      }
    } else {
      return console.log("[" + ts + "] " + msg + " ");
    }
  };

}).call(this);

//# sourceMappingURL=index.js.map
